# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
 branches:
   include:
     - main

jobs:
 - job: Build
   displayName: 'Build job'
   pool:
     vmImage: 'ubuntu-latest'
   steps:
     - task: UseJavaVersion@1
       inputs:
         versionSpec: '11'
         addToPath: true

     - script: mvn clean package
       displayName: 'Build Java application'

 - job: Deploy
   displayName: 'Deploy job'
   dependsOn: Build
   pool:
     vmImage: 'ubuntu-latest'
   steps:
     - task: Docker@2
       displayName: 'Build Docker image'
       inputs:
         command: 'build'
         containerRegistry: 'yourContainerRegistryConnection'
         repository: 'yourDockerRepository'
         tags: 'latest'
         buildContext: '$(System.DefaultWorkingDirectory)'

     - task: Kubernetes@1
       displayName: 'Deploy to AKS'
       inputs:
         connectionType: 'Azure Resource Manager'
         azureSubscriptionEndpoint: 'yourAzureSubscriptionConnection'
         azureResourceGroup: 'yourResourceGroup'
         kubernetesCluster: 'yourAKSCluster'
         command: 'apply'
         arguments: '-f kubernetes/deployment.yaml'